spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/smarthome
    driver-class-name:  com.mysql.jdbc.Driver
    username:  root
    password:  yd961118
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
