spring:
  datasource:
    url:  jdbc:mysql://10.8.162.52:3306/project9
    driver-class-name:  com.mysql.jdbc.Driver
    username:  root
    password:  yxq1227
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml